<?php

/**
 * This is the model base class for the table "tipo_reunion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoReunion".
 *
 * Columns in table "tipo_reunion" available as properties of the model,
 * followed by relations of table "tipo_reunion" available as properties of the model.
 *
 * @property string $CODIGO_TIPO
 * @property string $TIPO
 * @property integer $COD_USUARIO
 * @property string $FECHA_ACTUALIZACION
 *
 * @property Reunion[] $reunions
 */
abstract class BaseTipoReunion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'tipo_reunion';
    }

    public static function representingColumn() {
        return 'TIPO';
    }

    public function rules() {
        return array(
            array('TIPO, FECHA_ACTUALIZACION', 'required'),
            array('COD_USUARIO', 'numerical', 'integerOnly'=>true),
            array('TIPO', 'length', 'max'=>100),
            array('COD_USUARIO', 'default', 'setOnEmpty' => true, 'value' => null),
            array('CODIGO_TIPO, TIPO, COD_USUARIO, FECHA_ACTUALIZACION', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'reunions' => array(self::HAS_MANY, 'Reunion', 'CODIGO_TIPO'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'CODIGO_TIPO' => Yii::t('app', 'Codigo Tipo'),
                'TIPO' => Yii::t('app', 'Tipo'),
                'COD_USUARIO' => Yii::t('app', 'Cod Usuario'),
                'FECHA_ACTUALIZACION' => Yii::t('app', 'Fecha Actualizacion'),
                'reunions' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('CODIGO_TIPO', $this->CODIGO_TIPO, true);
        $criteria->compare('TIPO', $this->TIPO, true);
        $criteria->compare('COD_USUARIO', $this->COD_USUARIO);
        $criteria->compare('FECHA_ACTUALIZACION', $this->FECHA_ACTUALIZACION, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}