<?php

/**
 * This is the model base class for the table "movimiento_caja".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MovimientoCaja".
 *
 * Columns in table "movimiento_caja" available as properties of the model,
 * followed by relations of table "movimiento_caja" available as properties of the model.
 *
 * @property string $ID
 * @property string $ID_CAJA
 * @property integer $TIPO
 * @property string $VALOR
 * @property string $DESCRIPCION
 * @property string $FECHA
 * @property string $COD_USUARIO
 * @property string $FECHA_ACTUALIZACION
 *
 * @property Caja $iDCAJA
 */
abstract class BaseMovimientoCaja extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'movimiento_caja';
    }

    public static function representingColumn() {
        return 'FECHA_ACTUALIZACION';
    }

    public function rules() {
        return array(
            array('ID_CAJA, FECHA_ACTUALIZACION', 'required'),
            array('TIPO', 'numerical', 'integerOnly'=>true),
            array('ID_CAJA, COD_USUARIO', 'length', 'max'=>11),
            array('VALOR', 'length', 'max'=>8),
            array('DESCRIPCION', 'length', 'max'=>3000),
            array('FECHA', 'safe'),
            array('TIPO, VALOR, DESCRIPCION, FECHA, COD_USUARIO', 'default', 'setOnEmpty' => true, 'value' => null),
            array('ID, ID_CAJA, TIPO, VALOR, DESCRIPCION, FECHA, COD_USUARIO, FECHA_ACTUALIZACION', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'iDCAJA' => array(self::BELONGS_TO, 'Caja', 'ID_CAJA'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'ID_CAJA' => Yii::t('app', 'Id Caja'),
                'TIPO' => Yii::t('app', 'Tipo'),
                'VALOR' => Yii::t('app', 'Valor'),
                'DESCRIPCION' => Yii::t('app', 'Descripcion'),
                'FECHA' => Yii::t('app', 'Fecha'),
                'COD_USUARIO' => Yii::t('app', 'Cod Usuario'),
                'FECHA_ACTUALIZACION' => Yii::t('app', 'Fecha Actualizacion'),
                'iDCAJA' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID, true);
        $criteria->compare('ID_CAJA', $this->ID_CAJA);
        $criteria->compare('TIPO', $this->TIPO);
        $criteria->compare('VALOR', $this->VALOR, true);
        $criteria->compare('DESCRIPCION', $this->DESCRIPCION, true);
        $criteria->compare('FECHA', $this->FECHA, true);
        $criteria->compare('COD_USUARIO', $this->COD_USUARIO, true);
        $criteria->compare('FECHA_ACTUALIZACION', $this->FECHA_ACTUALIZACION, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}