<?php

/**
 * This is the model base class for the table "rubro".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Rubro".
 *
 * Columns in table "rubro" available as properties of the model,
 * followed by relations of table "rubro" available as properties of the model.
 *
 * @property string $ID
 * @property string $DESCRIPCION
 * @property string $V_UNITARIO
 * @property integer $PORCEN
 * @property string $FEC_CREACION
 * @property string $TIPO
 *
 * @property Detalle[] $detalles
 */
abstract class BaseRubro extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'rubro';
    }

    public static function representingColumn() {
        return 'DESCRIPCION';
    }

    public function rules() {
        return array(
            array('DESCRIPCION', 'required'),
            array('PORCEN', 'numerical', 'integerOnly'=>true),
            array('DESCRIPCION', 'length', 'max'=>50),
            array('V_UNITARIO', 'length', 'max'=>6),
            array('FEC_CREACION', 'safe'),
            array('V_UNITARIO, PORCEN, FEC_CREACION, TIPO', 'default', 'setOnEmpty' => true, 'value' => null),
            array('ID, DESCRIPCION, V_UNITARIO, PORCEN, FEC_CREACION,TIPO', 'safe', 'on'=>'search'),
            array('DESCRIPCION','unique','message'=>'El rubro ya esta creado'),
        );
    }

    public function relations() {
        return array(
            'detalles' => array(self::HAS_MANY, 'Detalle', 'ID_RUBRO'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'DESCRIPCION' => Yii::t('app', 'Descripción'),
                'V_UNITARIO' => Yii::t('app', 'Valor'),
                'PORCEN' => Yii::t('app', 'Interes por mora mensual (%)'),
                'FEC_CREACION' => Yii::t('app', 'Fecha de creación'),
                'TIPO' => Yii::t('app', 'Aplica a'),
                'detalles' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID, true);
        $criteria->compare('DESCRIPCION', $this->DESCRIPCION, true);
        $criteria->compare('V_UNITARIO', $this->V_UNITARIO, true);
        $criteria->compare('PORCEN', $this->PORCEN);
        $criteria->compare('FEC_CREACION', $this->FEC_CREACION, true);
        $criteria->compare('TIPO', $this->TIPO, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
      public function searchFacturas() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID, true);
        $criteria->compare('DESCRIPCION', $this->DESCRIPCION, true);
        $criteria->compare('V_UNITARIO', $this->V_UNITARIO, true);
        $criteria->compare('PORCEN', $this->PORCEN);
        $criteria->compare('FEC_CREACION', $this->FEC_CREACION, true);
        $criteria->compare('TIPO', 1, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
      public function searchRecibos() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID, true);
        $criteria->compare('DESCRIPCION', $this->DESCRIPCION, true);
        $criteria->compare('V_UNITARIO', $this->V_UNITARIO, true);
        $criteria->compare('PORCEN', $this->PORCEN);
        $criteria->compare('FEC_CREACION', $this->FEC_CREACION, true);
        $criteria->compare('TIPO', 2, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}