<?php

/**
 * This is the model base class for the table "cuota".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cuota".
 *
 * Columns in table "cuota" available as properties of the model,
 * followed by relations of table "cuota" available as properties of the model.
 *
 * @property string $ID
 * @property string $ID_DETALLE
 * @property string $FECHA
 * @property string $ABONO
 * @property string $SALDO
 * @property string $OBSERVACION
 * @property integer $COD_USUARIO
 * @property string $FECHA_ACTUALIZACION
 *
 * @property Detalle $iDDETALLE
 */
abstract class BaseCuota extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'cuota';
    }

    public static function representingColumn() {
        return 'ABONO';
    }

    public function rules() {
        return array(
            array('ABONO', 'required'),
            array('COD_USUARIO', 'numerical', 'integerOnly'=>true),
            array('ID_DETALLE', 'length', 'max'=>11),
            array('ABONO, SALDO', 'length', 'max'=>6),
            array('OBSERVACION', 'length', 'max'=>1000),
            array('FECHA', 'safe'),
            array('FECHA, SALDO, OBSERVACION, COD_USUARIO', 'default', 'setOnEmpty' => true, 'value' => null),
            array('ID, ID_DETALLE, FECHA, ABONO, SALDO, OBSERVACION, COD_USUARIO, FECHA_ACTUALIZACION', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'iDDETALLE' => array(self::BELONGS_TO, 'Detalle', 'ID_DETALLE'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ID' => Yii::t('app', 'ID'),
                'ID_DETALLE' => Yii::t('app', 'Id Detalle'),
                'FECHA' => Yii::t('app', 'Fecha'),
                'ABONO' => Yii::t('app', 'Abono'),
                'SALDO' => Yii::t('app', 'Saldo'),
                'OBSERVACION' => Yii::t('app', 'Observacion'),
                'COD_USUARIO' => Yii::t('app', 'Cod Usuario'),
                'FECHA_ACTUALIZACION' => Yii::t('app', 'Fecha Actualizacion'),
                'iDDETALLE' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ID', $this->ID, true);
        $criteria->compare('ID_DETALLE', $this->ID_DETALLE);
        $criteria->compare('FECHA', $this->FECHA, true);
        $criteria->compare('ABONO', $this->ABONO, true);
        $criteria->compare('SALDO', $this->SALDO, true);
        $criteria->compare('OBSERVACION', $this->OBSERVACION, true);
        $criteria->compare('COD_USUARIO', $this->COD_USUARIO);
        $criteria->compare('FECHA_ACTUALIZACION', $this->FECHA_ACTUALIZACION, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}