<?php

/**
 * This is the model base class for the table "nueva_imprecion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NuevaImprecion".
 *
 * Columns in table "nueva_imprecion" available as properties of the model,
 * followed by relations of table "nueva_imprecion" available as properties of the model.
 *
 * @property string $COD_IMPRESION
 * @property string $COD_RECIBO
 * @property integer $NUMERO
 * @property string $FECHA
 * @property integer $COD_USUARIO
 * @property string $FECHA_ACTUALIZACION
 *
 * @property NuevoRecibo $cODRECIBO
 */
abstract class BaseNuevaImprecion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'nueva_imprecion';
    }

    public static function representingColumn() {
        return 'FECHA_ACTUALIZACION';
    }

    public function rules() {
        return array(
            array('COD_RECIBO, NUMERO, FECHA_ACTUALIZACION', 'required'),
            array('NUMERO, COD_USUARIO', 'numerical', 'integerOnly'=>true),
            array('COD_RECIBO', 'length', 'max'=>11),
            array('FECHA', 'safe'),
            array('FECHA, COD_USUARIO', 'default', 'setOnEmpty' => true, 'value' => null),
            array('COD_IMPRESION, COD_RECIBO, NUMERO, FECHA, COD_USUARIO, FECHA_ACTUALIZACION', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'cODRECIBO' => array(self::BELONGS_TO, 'NuevoRecibo', 'COD_RECIBO'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'COD_IMPRESION' => Yii::t('app', 'Cod Impresion'),
                'COD_RECIBO' => Yii::t('app', 'Cod Recibo'),
                'NUMERO' => Yii::t('app', 'Numero'),
                'FECHA' => Yii::t('app', 'Fecha'),
                'COD_USUARIO' => Yii::t('app', 'Cod Usuario'),
                'FECHA_ACTUALIZACION' => Yii::t('app', 'Fecha Actualizacion'),
                'cODRECIBO' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('COD_IMPRESION', $this->COD_IMPRESION, true);
        $criteria->compare('COD_RECIBO', $this->COD_RECIBO);
        $criteria->compare('NUMERO', $this->NUMERO);
        $criteria->compare('FECHA', $this->FECHA, true);
        $criteria->compare('COD_USUARIO', $this->COD_USUARIO);
        $criteria->compare('FECHA_ACTUALIZACION', $this->FECHA_ACTUALIZACION, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}