<?php

/**
 * This is the model base class for the table "reunion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Reunion".
 *
 * Columns in table "reunion" available as properties of the model,
 * followed by relations of table "reunion" available as properties of the model.
 *
 * @property string $CODIGO_REUNION
 * @property string $CODIGO_TIPO
 * @property string $FECHA
 * @property string $HORA_INGRESO
 * @property string $TIEMPO_ESPERA
 * @property string $VALOR_ATRASO
 * @property string $VALOR_FUGA
 * @property string $VALOR_FALTA
 * @property string $ESTADO
 * @property integer $COD_USUARIO
 * @property string $FECHA_ACTUALIZACION
 *
 * @property Asistencia[] $asistencias
 * @property TipoReunion $cODIGOTIPO
 */
abstract class BaseReunion extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'reunion';
    }

    public static function representingColumn() {
        return 'CODIGO_REUNION';
    }

    public function rules() {
        return array(
            array('CODIGO_TIPO, FECHA, HORA_INGRESO, TIEMPO_ESPERA,', 'required'),
            array('COD_USUARIO', 'numerical', 'integerOnly'=>true),
            array('CODIGO_TIPO', 'length', 'max'=>11),
            array('VALOR_ATRASO, VALOR_FUGA, VALOR_FALTA', 'length', 'max'=>5),
            array('ESTADO', 'length', 'max'=>1),
            array('FECHA, HORA_INGRESO, TIEMPO_ESPERA, FECHA_ACTUALIZACION', 'safe'),
            array('FECHA, HORA_INGRESO, TIEMPO_ESPERA,  VALOR_ATRASO, VALOR_FUGA, VALOR_FALTA, ESTADO, COD_USUARIO, FECHA_ACTUALIZACION', 'default', 'setOnEmpty' => true, 'value' => null),
            array('CODIGO_REUNION, CODIGO_TIPO,FECHA, HORA_INGRESO, TIEMPO_ESPERA, VALOR_ATRASO, VALOR_FUGA, VALOR_FALTA, ESTADO, COD_USUARIO, FECHA_ACTUALIZACION', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'asistencias' => array(self::HAS_MANY, 'Asistencia', 'CODIGO_REUNION'),
            'cODIGOTIPO' => array(self::BELONGS_TO, 'TipoReunion', 'CODIGO_TIPO'),
            'usuarios' => array(self::BELONGS_TO, 'Usuario', 'COD_USUARIO'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'CODIGO_REUNION' => Yii::t('app', 'Código'),
                'CODIGO_TIPO' => Yii::t('app', 'Tipo de reunión'),
                'FECHA' => Yii::t('app', 'Fecha'),
                'HORA_INGRESO' => Yii::t('app', 'Hora de ingreso'),
                'TIEMPO_ESPERA' => Yii::t('app', 'Tiempo de espera'),
                 'VALOR_ATRASO' => Yii::t('app', 'Valor del atraso'),
                'VALOR_FUGA' => Yii::t('app', 'Valor de fuga'),
                'VALOR_FALTA' => Yii::t('app', 'Valor por falta'),
                'ESTADO' => Yii::t('app', 'Estado'),
                'COD_USUARIO' => Yii::t('app', 'Actualizado por:'),
                'FECHA_ACTUALIZACION' => Yii::t('app', 'Actualizado el:'),
                'asistencias' => null,
                'cODIGOTIPO' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('CODIGO_REUNION', $this->CODIGO_REUNION, true);
        $criteria->compare('CODIGO_TIPO', $this->CODIGO_TIPO);
        
        $criteria->compare('FECHA', $this->FECHA, true);
        $criteria->compare('HORA_INGRESO', $this->HORA_INGRESO, true);
        $criteria->compare('TIEMPO_ESPERA', $this->TIEMPO_ESPERA, true);
        $criteria->compare('VALOR_ATRASO', $this->VALOR_ATRASO, true);
        $criteria->compare('VALOR_FUGA', $this->VALOR_FUGA, true);
        $criteria->compare('VALOR_FALTA', $this->VALOR_FALTA, true);
        $criteria->compare('ESTADO', $this->ESTADO, true);
        $criteria->compare('COD_USUARIO', $this->COD_USUARIO);
        $criteria->compare('FECHA_ACTUALIZACION', $this->FECHA_ACTUALIZACION, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
             'sort'=>array(
                 'defaultOrder'=>'CODIGO_REUNION DESC',
               ),
        ));
    }
    public function searchAsistencia() {
        $criteria = new CDbCriteria;

        $criteria->compare('CODIGO_REUNION', $this->CODIGO_REUNION, true);
        $criteria->compare('CODIGO_TIPO', $this->CODIGO_TIPO);
        
        $criteria->compare('FECHA', $this->FECHA, true);
        $criteria->compare('HORA_INGRESO', $this->HORA_INGRESO, true);
        $criteria->compare('TIEMPO_ESPERA', $this->TIEMPO_ESPERA, true);
        $criteria->compare('VALOR_ATRASO', $this->VALOR_ATRASO, true);
        $criteria->compare('VALOR_FUGA', $this->VALOR_FUGA, true);
        $criteria->compare('VALOR_FALTA', $this->VALOR_FALTA, true);
        $criteria->compare('ESTADO', 1, true);
        $criteria->compare('COD_USUARIO', $this->COD_USUARIO);
        $criteria->compare('FECHA_ACTUALIZACION', $this->FECHA_ACTUALIZACION, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
             'sort'=>array(
                 'defaultOrder'=>'CODIGO_REUNION DESC',
               ),
            
            
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}