<?php

/**
 * This is the model base class for the table "Rol".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Rol".
 *
 * Columns in table "Rol" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id_rol
 * @property string $Rol
 *
 */
abstract class BaseRol extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'Rol';
    }

    public static function representingColumn() {
        return 'Rol';
    }

    public function rules() {
        return array(
            array('Rol', 'length', 'max'=>20),
            array('Rol', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_rol, Rol', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id_rol' => Yii::t('app', 'Id Rol'),
                'Rol' => Yii::t('app', 'Rol'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id_rol', $this->id_rol, true);
        $criteria->compare('Rol', $this->Rol, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}